### PR TITLE
Cleanup/refactor of some tests

### PR DESCRIPTION
**Pull request by laurence-bird**

### CODE REVIEW

**Comment by fleetwoods** [comment]
I am not completely sold on using scalacheck for generating data for single tests. Feel like for a specific test you want it to be deterministic and repeatable and using scalacheck to provide further confidence.

**Comment by cb372** [comment]
@fleetwoods I can understand that. But I think @laurence-bird has struck a nice balance here: use scalacheck to generate all the boring fields you don't care about, then do a `.copy` on the result to override only the fields you do care about.

The benefit of this approach is that it makes the tests easier to maintain. You don't have to go and update every piece of test data just because we added a new field to the schema.

**Comment by cb372** [comment]
I'm 👍 on this PR, but also happy if you two want to discuss it further

**Comment by fleetwoods** [comment]
All good with me

**Comment by ovo-comms-circleci** [comment]
This PR was successfully deployed to production by [CircleCI build 69](https://circleci.com/gh/ovotech/comms-audit-log/69) at 2017-02-03 10:40 GMT.

**Pull request merged**
